### bazaar.ftl — generated by urd
### Run `quest gen-l10n bazaar.urd` to regenerate.
### Source: bazaar.urd

## label: start
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold)

bazaar-start-menu_1-line_1 = The Wandering Bazaar follows the ancient trade routes.
    We appear where weary travelers need us most.

# menu: bazaar-start-menu_1
bazaar-start-menu_1-browse_the_wares = Browse the wares
bazaar-start-menu_1-ask_about_the_bazaar = Ask about the bazaar
bazaar-start-menu_1-walk_away = Walk away

bazaar-start-line_2 = Welcome! I am Elara, purveyor of fine curiosities.
    Might I interest you in a Health Potion today?

bazaar-start-line_1 = You step into the Wandering Bazaar.
    Canvas stalls stretch in every direction, lit by swaying lanterns.

## label: farewell
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold)

bazaar-farewell-if_1-line_2 = That potion has saved many a life. May it save yours too.

# interpolation: $gold
bazaar-farewell-if_1-line_1 = You leave with a potion in your pack and { $gold } gold.

bazaar-farewell-if_1-line_4 = Return whenever you need something. I will be here.

# interpolation: $gold
bazaar-farewell-if_1-line_3 = You leave the Wandering Bazaar with { $gold } gold and your curiosity intact.

