### merchant.ftl — generated by urd
### Run `quest gen-l10n merchant.urd` to regenerate.
### Source: merchant.urd

## label: merchant::browse
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold), $item (urd: item)

# menu: merchant-browse-menu_1
merchant-browse-menu_1-buy_it_for_price_gold = Buy it for { $price } gold
merchant-browse-menu_1-try_to_haggle = Try to haggle
merchant-browse-menu_1-never_mind = Never mind

# interpolation: $price
merchant-browse-line_1 = Behold: the Health Potion! I ask { $price } gold — a true bargain.

## label: merchant::haggle
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold)

merchant-haggle-menu_1-line_1 = Another time, friend. Safe roads to you.

# menu: merchant-haggle-menu_1
merchant-haggle-menu_1-deal_price_gold = Deal! { $price } gold
merchant-haggle-menu_1-too_rich_for_my_blood = Too rich for my blood

merchant-haggle-line_1 = You drive a hard bargain.
    Twenty-five gold — that is my absolute lowest. Take it or leave it.

## label: merchant::buy
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold)

# interpolation: $gold
merchant-buy-if_1-line_1 = Splendid! The potion is yours. You now have { $gold } gold.

# interpolation: $gold, $price
merchant-buy-if_1-line_2 = You only have { $gold } gold — not quite { $price }. Come back when fortune smiles.

