### pl-PL/bazaar.ftl
### Polski (Polska) — tłumaczenie
###
### Cechy Fluent użyte w tym pliku:
###   { $gold -> [0] … [one] … [few] … *[other] … }  — reguły liczby mnogiej
###   wieloliniowe wartości (z wcięciem)               — kontynuacja tekstu

### bazaar.ftl — generated by urd
### Run `quest gen-l10n bazaar.urd` to regenerate.
### Source: bazaar.urd

## label: start
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold)

bazaar-start-menu_1-line_1 = Wędrujący Bazar podąża pradawnymi szlakami handlowymi.
    Pojawiamy się tam, gdzie zmęczeni wędrowcy potrzebują nas najbardziej.

# menu: bazaar-start-menu_1
bazaar-start-menu_1-browse_the_wares = Przejrzyj towary
bazaar-start-menu_1-ask_about_the_bazaar = Zapytaj o bazar
bazaar-start-menu_1-walk_away = Odejdź

bazaar-start-line_2 = Witaj! Jestem Elara, handlarka wyjątkowych osobliwości.
    Czy mogę zainteresować cię dzisiaj miksturą zdrowia?

bazaar-start-line_1 = Wchodzisz do Wędrującego Bazaru.
    Płócienne stragany rozciągają się w każdą stronę, oświetlone kołyszącymi się lampionami.

## label: farewell
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold)

bazaar-farewell-if_1-line_2 = Ta mikstura uratowała niejedne życie. Obyś żył długo i szczęśliwie.

# interpolation: $gold
bazaar-farewell-if_1-line_1 =
    Opuszczasz bazar z miksturą w plecaku i { $gold ->
        [0]     bez ani jednej złotej monety — zdrowie kosztuje
        [one]   jedną złotą monetą w kieszeni
        [few]   { $gold } złotymi monetami
       *[other] { $gold } złotymi monetami w sakiewce
    }.

bazaar-farewell-if_1-line_4 = Wróć, gdy czegoś będziesz potrzebował. Będę tu na ciebie czekać.

# interpolation: $gold
bazaar-farewell-if_1-line_3 =
    Opuszczasz Wędrujący Bazar z { $gold ->
        [0]     pustą sakiewką
        [one]   jedną złotą monetą
        [few]   { $gold } złotymi monetami
       *[other] { $gold } złotymi monetami
    } i niezaspokojoną ciekawością.
