### pl-PL/merchant.ftl
### Polski (Polska) — tłumaczenie
###
### Cechy Fluent użyte w tym pliku:
###   { $gold -> [0] … [one] … [few] … *[other] … }        — reguły liczby mnogiej
###   { $item -> [health_potion] … *[other] … }             — ID przedmiotu → forma gramatyczna
###   { $price -> [one] … [few] … *[other] … }              — odmiana ceny
###
### Wzorzec ID przedmiotu:
###   Skrypt urd przekazuje item = "health_potion" (identyfikator, nigdy surowy tekst).
###   Ten plik mapuje identyfikator na poprawną gramatycznie formę polską.
###   Kluczowe: TEN SAM identyfikator daje RÓŻNE formy zależnie od kontekstu zdania:
###     "Oto: mikstura zdrowia"   — mianownik (podmiot/orzecznik po „Oto:")
###     "Kup miksturę zdrowia"    — biernik  (dopełnienie bliższe po „kup/weź")
###   To niemożliwe do osiągnięcia, gdy urd przekazuje surowy łańcuch "Health Potion".

### merchant.ftl — generated by urd
### Run `quest gen-l10n merchant.urd` to regenerate.
### Source: merchant.urd

## label: start
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold)

merchant-start-menu_1-line_1 = Wędrujący Bazar podąża pradawnymi szlakami handlowymi.
    Pojawiamy się tam, gdzie zmęczeni wędrowcy potrzebują nas najbardziej.

# menu: merchant-start-menu_1
merchant-start-menu_1-browse_the_wares = Przejrzyj towary
merchant-start-menu_1-ask_about_the_bazaar = Zapytaj o bazar
merchant-start-menu_1-walk_away = Odejdź

merchant-start-line_1 = Wchodzisz do Wędrującego Bazaru.
    Płócienne stragany rozciągają się w każdą stronę, oświetlone kołyszącymi się lampionami.

merchant-start-line_2 = Witaj! Jestem Elara, handlarka wyjątkowych osobliwości.
    Czy mogę zainteresować cię dzisiaj miksturą zdrowia?

## label: browse
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold), $item (urd: item)
# $item to identyfikator przedmiotu (np. "health_potion") — użyj selektora, by uzyskać
# poprawną formę gramatyczną.  Dodaj nowe ramię dla każdego nowego przedmiotu w grze.

# menu: merchant-browse-menu_1
# Biernik — przedmiot jest dopełnieniem bliższym czasownika "kup".
merchant-browse-menu_1-buy_it_for_price_gold =
    Kup { $item ->
        [health_potion] miksturę zdrowia
        [mana_potion]   miksturę many
       *[other]         { $item }
    } za { $price ->
        [one]   { $price } złoty
        [few]   { $price } złote
       *[other] { $price } złotych
    }
merchant-browse-menu_1-try_to_haggle = Spróbuj się potargować
merchant-browse-menu_1-never_mind = Nieważne

# interpolation: $price
# $item jest wstrzykiwany przez @fluent — selektor poniżej mapuje go na formę mianownikową.
# "Oto:" wymaga mianownika: "mikstura zdrowia", NIE biernika "miksturę zdrowia".
merchant-browse-line_1 =
    Oto: { $item ->
        [health_potion] mikstura zdrowia
        [mana_potion]   mikstura many
       *[other]         { $item }
    }! Proszę { $price ->
        [one]   { $price } złoty — to prawdziwa okazja.
        [few]   { $price } złote — to prawdziwa okazja.
       *[other] { $price } złotych — to prawdziwa okazja.
    }

## label: haggle
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold)

merchant-haggle-menu_1-line_1 = Innym razem, przyjacielu. Szczęśliwej drogi.

# menu: merchant-haggle-menu_1
merchant-haggle-menu_1-deal_price_gold = Zgoda! { $price ->
    [one]   { $price } złoty
    [few]   { $price } złote
   *[other] { $price } złotych
}
merchant-haggle-menu_1-too_rich_for_my_blood = Za drogo dla mnie

merchant-haggle-line_1 = Twardo się targowałeś.
    Dwadzieścia pięć złotych — to moja absolutnie najniższa cena. Bierzesz czy nie?

## label: buy
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold)

# interpolation: $gold
merchant-buy-if_1-line_1 = Znakomicie! Mikstura jest twoja. Masz teraz { $gold ->
    [0]     ani grosza — warta każdej monety!
    [one]   tylko jedną złotą monetę.
    [few]   { $gold } złote monety.
   *[other] { $gold } złotych monet.
}

# interpolation: $gold, $price
merchant-buy-if_1-line_2 = Masz tylko { $gold } złotych — brakuje ci do { $price } złotych. Wróć, gdy uśmiechnie się do ciebie fortuna.

## label: farewell
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold)

# interpolation: $gold
merchant-farewell-if_1-line_1 =
    Opuszczasz bazar z miksturą w plecaku i { $gold ->
        [0]     bez ani jednej złotej monety — zdrowie kosztuje
        [one]   jedną złotą monetą w kieszeni
        [few]   { $gold } złotymi monetami
       *[other] { $gold } złotymi monetami w sakiewce
    }.

merchant-farewell-if_1-line_2 = Ta mikstura uratowała niejedne życie. Obyś żył długo i szczęśliwie.

# interpolation: $gold
merchant-farewell-if_1-line_3 =
    Opuszczasz Wędrujący Bazar z { $gold ->
        [0]     pustą sakiewką
        [one]   jedną złotą monetą
        [few]   { $gold } złotymi monetami
       *[other] { $gold } złotymi monetami
    } i niezaspokojoną ciekawością.

merchant-farewell-if_1-line_4 = Wróć, gdy czegoś będziesz potrzebował. Będę tu na ciebie czekać.

## label: _end
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold)
