### pl-PL/merchant.ftl
### Polski (Polska) — tłumaczenie
###
### Cechy Fluent użyte w tym pliku:
###   { $gold -> [0] … [one] … [few] … *[other] … }  — reguły liczby mnogiej
###   { $item }, { $price }                           — zmienne interpolowane

### merchant.ftl — generated by urd
### Run `quest gen-l10n merchant.urd` to regenerate.
### Source: merchant.urd

## label: start
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold)

merchant-start-menu_1-line_1 = Wędrujący Bazar podąża pradawnymi szlakami handlowymi.
    Pojawiamy się tam, gdzie zmęczeni wędrowcy potrzebują nas najbardziej.

# menu: merchant-start-menu_1
merchant-start-menu_1-browse_the_wares = Przejrzyj towary
merchant-start-menu_1-ask_about_the_bazaar = Zapytaj o bazar
merchant-start-menu_1-walk_away = Odejdź

merchant-start-line_1 = Witaj! Jestem Elara, handlarka wyjątkowych osobliwości.
    Czy mogę zainteresować cię dzisiaj miksturą zdrowia?

merchant-start-line_2 = Wchodzisz do Wędrującego Bazaru.
    Płócienne stragany rozciągają się w każdą stronę, oświetlone kołyszącymi się lampionami.

## label: browse
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold), $item (urd: item_name)

# menu: merchant-browse-menu_1
merchant-browse-menu_1-buy_it_for_price_gold = Kup za { $price ->
    [one]   { $price } złoty
    [few]   { $price } złote
   *[other] { $price } złotych
}
merchant-browse-menu_1-try_to_haggle = Spróbuj się potargować
merchant-browse-menu_1-never_mind = Nieważne

# interpolation: $item_name, $price
# Note: $item is the @fluent alias for item_name — both are available; $item is preferred here.
merchant-browse-line_1 = Oto: { $item }! Proszę { $price ->
    [one]   { $price } złoty — to prawdziwa okazja.
    [few]   { $price } złote — to prawdziwa okazja.
   *[other] { $price } złotych — to prawdziwa okazja.
}

## label: haggle
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold)

merchant-haggle-menu_1-line_1 = Innym razem, przyjacielu. Szczęśliwej drogi.

# menu: merchant-haggle-menu_1
merchant-haggle-menu_1-deal_price_gold = Zgoda! { $price ->
    [one]   { $price } złoty
    [few]   { $price } złote
   *[other] { $price } złotych
}
merchant-haggle-menu_1-too_rich_for_my_blood = Za drogo dla mnie

merchant-haggle-line_1 = Twardo się targowałeś.
    Dwadzieścia pięć złotych — to moja absolutnie najniższa cena. Bierzesz czy nie?

## label: buy
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold)

# interpolation: $gold
merchant-buy-if_1-line_1 = Znakomicie! Mikstura jest twoja. Masz teraz { $gold ->
    [0]     ani grosza — warta każdej monety!
    [one]   tylko jedną złotą monetę.
    [few]   { $gold } złote monety.
   *[other] { $gold } złotych monet.
}

# interpolation: $gold, $price
merchant-buy-if_1-line_2 = Masz tylko { $gold } złotych — brakuje ci do { $price } złotych. Wróć, gdy uśmiechnie się do ciebie fortuna.

## label: farewell
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold)

merchant-farewell-if_1-line_1 = Ta mikstura uratowała niejedne życie. Obyś żył długo i szczęśliwie.

# interpolation: $gold
merchant-farewell-if_1-line_2 =
    Opuszczasz bazar z miksturą w plecaku i { $gold ->
        [0]     bez ani jednej złotej monety — zdrowie kosztuje
        [one]   jedną złotą monetą w kieszeni
        [few]   { $gold } złotymi monetami
       *[other] { $gold } złotymi monetami w sakiewce
    }.

merchant-farewell-if_1-line_3 = Wróć, gdy czegoś będziesz potrzebował. Będę tu na ciebie czekać.

# interpolation: $gold
merchant-farewell-if_1-line_4 =
    Opuszczasz Wędrujący Bazar z { $gold ->
        [0]     pustą sakiewką
        [one]   jedną złotą monetą
        [few]   { $gold } złotymi monetami
       *[other] { $gold } złotymi monetami
    } i niezaspokojoną ciekawością.

## label: _end
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold)
