### pl-PL/merchant.ftl
### Polski (Polska) — tłumaczenie
###
### Cechy Fluent użyte w tym pliku:
###   { $gold -> [0] … [one] … [few] … *[other] … }  — reguły liczby mnogiej
###   { $item -> [health_potion] … *[other] … }       — selektor identyfikatora przedmiotu
###   { $price }, { $gold }                            — zmienne interpolowane

### merchant.ftl — generated by urd
### Run `quest gen-l10n merchant.urd` to regenerate.
### Source: merchant.urd

## label: merchant::browse
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold), $item (urd: item)

# menu: merchant-browse-menu_1
merchant-browse-menu_1-buy_it_for_price_gold = Kup { $item ->
    [health_potion] miksturę zdrowia
    [mana_potion]   miksturę many
   *[other]         to
} za { $price ->
    [one]   { $price } złoty
    [few]   { $price } złote
   *[other] { $price } złotych
}
merchant-browse-menu_1-try_to_haggle = Spróbuj się potargować
merchant-browse-menu_1-never_mind = Nieważne

# interpolation: $price
merchant-browse-line_1 = Oto: { $item ->
    [health_potion] mikstura zdrowia
    [mana_potion]   mikstura many
   *[other]         { $item }
}! Proszę { $price ->
    [one]   { $price } złoty
    [few]   { $price } złote
   *[other] { $price } złotych
} — to prawdziwa okazja.

## label: merchant::haggle
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold)

merchant-haggle-menu_1-line_1 = Innym razem, przyjacielu. Szczęśliwej drogi.

# menu: merchant-haggle-menu_1
merchant-haggle-menu_1-deal_price_gold = Zgoda! { $price ->
    [one]   { $price } złoty
    [few]   { $price } złote
   *[other] { $price } złotych
}
merchant-haggle-menu_1-too_rich_for_my_blood = Za drogo dla mnie

merchant-haggle-line_1 = Twardo się targowałeś.
    Dwadzieścia pięć złotych — to moja absolutnie najniższa cena. Bierzesz czy nie?

## label: merchant::buy
# @fluent variables: $has_potion (urd: has_potion), $price (urd: price), $gold (urd: gold)

# interpolation: $gold
merchant-buy-if_1-line_1 = Znakomicie! Mikstura jest twoja. Masz teraz { $gold ->
    [0]     ani grosza — warta każdej monety!
    [one]   tylko jedną złotą monetę.
    [few]   { $gold } złote monety.
   *[other] { $gold } złotych monet.
}

# interpolation: $gold, $price
merchant-buy-if_1-line_2 = Masz tylko { $gold } złotych — brakuje ci do { $price } złotych. Wróć, gdy uśmiechnie się do ciebie fortuna.
